/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jeanp
 */
public class StartFrame extends javax.swing.JFrame {
    int portNum=5001;
    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jl_showRoom.setVisible(false);
        jb_joinRoom.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_backGround = new javax.swing.JPanel();
        jl_showImage = new javax.swing.JLabel();
        jb_newGame = new javax.swing.JButton();
        jl_or = new javax.swing.JLabel();
        jtf_enterRoom = new javax.swing.JTextField();
        jl_showRoom = new javax.swing.JLabel();
        jb_joinRoom = new javax.swing.JButton();
        jb_instructions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_backGround.setBackground(new java.awt.Color(255, 255, 255));
        jp_backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_showImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/startImg.gif"))); // NOI18N
        jp_backGround.add(jl_showImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 340));

        jb_newGame.setBackground(new java.awt.Color(0, 153, 153));
        jb_newGame.setForeground(new java.awt.Color(255, 255, 255));
        jb_newGame.setText("New Game");
        jb_newGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_newGameActionPerformed(evt);
            }
        });
        jp_backGround.add(jb_newGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 220, 50));

        jl_or.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jl_or.setForeground(new java.awt.Color(0, 102, 102));
        jl_or.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_or.setText("OR");
        jp_backGround.add(jl_or, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 80, 70));

        jtf_enterRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_enterRoom.setForeground(new java.awt.Color(153, 153, 153));
        jtf_enterRoom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_enterRoom.setText("Enter a room to join");
        jtf_enterRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_enterRoomMouseClicked(evt);
            }
        });
        jp_backGround.add(jtf_enterRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 200, 40));

        jl_showRoom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_showRoom.setForeground(new java.awt.Color(0, 153, 153));
        jl_showRoom.setText("Yo've joined room: 5001");
        jp_backGround.add(jl_showRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 220, 70));

        jb_joinRoom.setBackground(new java.awt.Color(0, 153, 153));
        jb_joinRoom.setForeground(new java.awt.Color(255, 255, 255));
        jb_joinRoom.setText("Join room");
        jb_joinRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_joinRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_joinRoomActionPerformed(evt);
            }
        });
        jp_backGround.add(jb_joinRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, 200, 50));

        jb_instructions.setBackground(new java.awt.Color(0, 153, 153));
        jb_instructions.setForeground(new java.awt.Color(255, 255, 255));
        jb_instructions.setText("Instructions");
        jb_instructions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_instructionsActionPerformed(evt);
            }
        });
        jp_backGround.add(jb_instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_backGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_backGround, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_newGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_newGameActionPerformed
        jl_showRoom.setVisible(true);
        try {
            MainFrame mfServer = new MainFrame();
            mfServer.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(StartFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jb_newGameActionPerformed

    private void jb_joinRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_joinRoomActionPerformed
        if(Integer.parseInt(jtf_enterRoom.getText()) == portNum){
            MainFrameClient mfClient = new MainFrameClient();
             new MainFrameClient().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No existe la sala con ese numero");
        }
    }//GEN-LAST:event_jb_joinRoomActionPerformed

    private void jtf_enterRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_enterRoomMouseClicked
        jtf_enterRoom.setText("");
        jb_joinRoom.setVisible(true);
    }//GEN-LAST:event_jtf_enterRoomMouseClicked

    private void jb_instructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_instructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_instructionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_instructions;
    private javax.swing.JButton jb_joinRoom;
    private javax.swing.JButton jb_newGame;
    private javax.swing.JLabel jl_or;
    private javax.swing.JLabel jl_showImage;
    private javax.swing.JLabel jl_showRoom;
    private javax.swing.JPanel jp_backGround;
    private javax.swing.JTextField jtf_enterRoom;
    // End of variables declaration//GEN-END:variables
}
